const PRIMARY_COLOR = "#26a69a"
const PRIMARY_LIGHT_COLOR = "#64d8cb"
const PRIMARY_DARK_COLOR = "#00766c"
const SECONDARY_COLOR = "#ffab00"
const SECONDARY_LIGHT_COLOR = "#ffdd4b"
const SECONDARY_DARK_COLOR = "#c67c00"
const PRIMARY_TEXT_COLOR = "#FFFFFF"
const SECONDARY_TEXT_COLOR = "#000000"

export default {
    PRIMARY_COLOR,
    PRIMARY_LIGHT_COLOR,
    PRIMARY_DARK_COLOR,
    SECONDARY_COLOR,
    SECONDARY_LIGHT_COLOR,
    SECONDARY_DARK_COLOR,
    PRIMARY_TEXT_COLOR,
    SECONDARY_TEXT_COLOR,

}